Repository freemocap/freemocap, pull requests merged in 2023-07, with the labels that each got.

#439 Fix Pydantic Errors
  freemocap/core_processes/detecting_things_in_2d_images/mediapipe_stuff/mediapipe_skeleton_detector.py
  freemocap/data_layer/recording_models/post_processing_parameter_models.py
  freemocap/gui/qt/widgets/control_panel/process_mocap_data_panel/parameter_groups/create_parameter_groups.py
Labels: bug

#451 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, ready for review

#421 Save gui state
  freemocap/core_processes/capture_volume_calibration/charuco_stuff/default_charuco_square_size.py
  freemocap/gui/qt/actions_and_menus/actions.py
  freemocap/gui/qt/actions_and_menus/menu_bar.py
  freemocap/gui/qt/main_window/freemocap_main_window.py
  freemocap/gui/qt/utilities/save_and_load_gui_state.py
  freemocap/gui/qt/widgets/camera_controller_group_box.py
  freemocap/gui/qt/widgets/control_panel/calibration_control_panel.py
  freemocap/gui/qt/widgets/control_panel/process_mocap_data_panel/process_motion_capture_data_panel.py
  freemocap/gui/qt/widgets/home_widget.py
  freemocap/system/paths_and_filenames/file_and_folder_names.py
  freemocap/system/paths_and_filenames/path_getters.py
Labels: ready for review

#442 Find linux executable
  freemocap/data_layer/export_data/blender_stuff/get_best_guess_of_blender_path.py
  freemocap/gui/qt/widgets/control_panel/visualization_control_panel.py
Labels: ready for review

#420 Load sample data button
  freemocap/gui/qt/actions_and_menus/actions.py
  freemocap/gui/qt/actions_and_menus/menu_bar.py
  freemocap/gui/qt/main_window/freemocap_main_window.py
  freemocap/gui/qt/workers/download_sample_data_thread_worker.py
  freemocap/system/paths_and_filenames/file_and_folder_names.py
  freemocap/system/paths_and_filenames/path_getters.py
  freemocap/utilities/download_sample_data.py
Labels: ready for review

#379 Add option to synchronize videos on import
  freemocap/gui/qt/main_window/freemocap_main_window.py
  freemocap/gui/qt/widgets/import_videos_wizard.py
  freemocap/gui/qt/workers/synchronize_videos_thread_worker.py
  pyproject.toml
Labels: ready for review

#434 Console Log Fix
  freemocap/core_processes/process_motion_capture_videos/process_recording_folder.py
  freemocap/gui/qt/freemocap_main.py
  freemocap/gui/qt/main_window/freemocap_main_window.py
  freemocap/gui/qt/widgets/control_panel/process_mocap_data_panel/process_motion_capture_data_panel.py
  freemocap/gui/qt/widgets/log_view_widget.py
  freemocap/gui/qt/workers/process_motion_capture_data_thread_worker.py
  freemocap/system/logging/configure_logging.py
  freemocap/system/logging/queue_logger.py
Labels: ready for review

#452 Remove final Darkmode Bugs
  freemocap/gui/qt/style_sheet/qt_style_sheet.css
  freemocap/gui/qt/style_sheet/qt_style_sheet.scss
Labels: ready for review

#447 Add notes about testing in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ready for review

#456 Generate Jupyter Notebook w/o papermill
  freemocap/core_processes/process_motion_capture_videos/process_recording_headless.py
  freemocap/data_layer/export_data/generate_jupyter_notebook/generate_jupyter_notebook.py
  freemocap/data_layer/generate_jupyter_notebook/__init__.py
  freemocap/data_layer/generate_jupyter_notebook/freemocap_template.ipynb
  freemocap/data_layer/generate_jupyter_notebook/generate_jupyter_notebook.py
  pyproject.toml
Labels: ready for review

#455 Flake 8 adoption
  .flake8
  .github/workflows/linting-flake8.yml
  .github/workflows/version-testing.yml
  experimental/batch_process/batch_process.py
  experimental/batch_process/headless_calibration.py
  freemocap/__init__.py
  freemocap/__main__.py
  freemocap/core_processes/capture_volume_calibration/charuco_stuff/charuco_board_definition.py
  freemocap/core_processes/detecting_things_in_2d_images/mediapipe_stuff/mediapipe_skeleton_detector.py
  freemocap/core_processes/post_process_skeleton_data/calculate_center_of_mass.py
  freemocap/core_processes/process_motion_capture_videos/process_recording_folder.py
  freemocap/core_processes/process_motion_capture_videos/process_recording_headless.py
  freemocap/data_layer/export_data/blender_stuff/blender_bpy_export_scripts/freemocap_blender_megascript_take2.py
  freemocap/data_layer/export_data/blender_stuff/call_blender_subprocess_methods.py
  freemocap/data_layer/export_data/blender_stuff/export_to_blender.py
  freemocap/data_layer/export_data/blender_stuff/get_best_guess_of_blender_path.py
  freemocap/data_layer/generate_jupyter_notebook/generate_jupyter_notebook.py
  freemocap/data_layer/recording_models/recording_info_model.py
  freemocap/gui/qt/freemocap_main.py
  freemocap/gui/qt/main_window/freemocap_main_window.py
  freemocap/gui/qt/style_sheet/scss_file_watcher.py
  freemocap/gui/qt/widgets/camera_controller_group_box.py
  freemocap/gui/qt/widgets/central_tab_widget.py
  freemocap/gui/qt/widgets/control_panel/calibration_control_panel.py
  freemocap/gui/qt/widgets/control_panel/control_panel_dock_widget.py
  freemocap/gui/qt/widgets/control_panel/process_mocap_data_panel/parameter_groups/create_3d_triangulation_parameter_group.py
  freemocap/gui/qt/widgets/control_panel/process_mocap_data_panel/parameter_groups/create_parameter_groups.py
  freemocap/gui/qt/widgets/log_view_widget.py
  freemocap/gui/qt/workers/anipose_calibration_thread_worker.py
  freemocap/gui/qt/workers/download_sample_data_thread_worker.py
  freemocap/gui/qt/workers/synchronize_videos_thread_worker.py
  freemocap/system/logging/configure_logging.py
  freemocap/system/open_file.py
  freemocap/system/paths_and_filenames/path_getters.py
  freemocap/system/user_data/pipedream_pings.py
  freemocap/tests/test_total_body_center_of_mass_data_shape.py
  freemocap/utilities/create_nested_dict_from_pydantic.py
  freemocap/utilities/download_sample_data.py
  noxfile.py
  pyproject.toml
Labels: ready for review

#457 Geometry unit testing
  freemocap/tests/test_geometry_utilities.py
  freemocap/utilities/geometry/rotate_by_90_degrees_around_x_axis.py
  freemocap/utilities/get_video_paths.py
Labels: ready for review

#460 Welcome screen
  freemocap/gui/qt/freemocap_main.py
  freemocap/gui/qt/main_window/freemocap_main_window.py
  freemocap/gui/qt/style_sheet/qt_style_sheet.css
  freemocap/gui/qt/style_sheet/qt_style_sheet.scss
  freemocap/gui/qt/utilities/save_and_load_gui_state.py
  freemocap/gui/qt/widgets/welcome_screen_dialog.py
Labels: ready for review
