Repository freemocap/freemocap, pull requests merged in 2024-12, with the labels that each got.

#656 fix docs and privacy policy links
  freemocap/gui/qt/widgets/home_widget.py
Labels: Minor, ready for review

#652 Add uv override for opencv-python
  pyproject.toml
Labels: Minor, ready for review

#658 Update addon version
  .github/workflows/python-testing.yml
  .github/workflows/version-testing-1.yml
  README.md
  freemocap/core_processes/export_data/blender_stuff/export_to_blender/methods/ajc_addon/run_simple.py
  noxfile.py
  pyproject.toml
Labels: Minor, ready for review

#659 Vet actions with zizmor
  .github/workflows/ci.yml
  .github/workflows/coverage-testing.yml
  .github/workflows/flit_publish_to_pypi.yml
  .github/workflows/lint_actions_zizmor.yml
  .github/workflows/linting-flake8.yml
  .github/workflows/linux_installer.yml
  .github/workflows/mac_installer.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/python-testing.yml
  .github/workflows/version-testing-1.yml
  .github/workflows/version-testing-2.yml
  .github/workflows/windows_installer.yml
Labels: ready for review

#662 fix path to center of mass in notebook output
  freemocap/data_layer/generate_jupyter_notebook/freemocap_template.ipynb
Labels: bug, Minor, data output, ready for review

#660 Update pyproject.toml
  pyproject.toml
Labels: ready for review

#661 add tidy csv option
  freemocap/data_layer/data_saver/data_loader.py
  freemocap/data_layer/data_saver/data_saver.py
Labels: ready for review
